#!/usr/bin/env python3

from argparse import ArgumentParser, Namespace
from os import chdir, close, environ, execv, kill, read, setgid, setuid, write
from typing import Any
from pam import pam
from pty import fork
from pwd import getpwnam
from socket import SO_REUSEADDR, socket as Socket, SOL_SOCKET
from selectors import DefaultSelector, EVENT_READ, SelectorKey
from sys import stdin, stderr, stdout
from termios import tcgetattr, tcsetattr, TCSADRAIN
from tty import setraw

BUFFER_SIZE: int = 4096

argument_parser: ArgumentParser = ArgumentParser()
argument_parser.add_argument('-s', '--server', action = 'store_true')
argument_parser.add_argument('-a', '--address', default = '127.0.0.1', type = str)
argument_parser.add_argument('-p', '--port', default = 8078, type = int)
argument_parser.add_argument('-u', '--username', type = str)
arguments: Namespace = argument_parser.parse_args(
)

server: bool = arguments.server
address: str = arguments.address
port: int = arguments.port
endpoint: tuple[str, int] = (address, port)
username: str = arguments.username
if not server and username is None:
    raise ValueError

if server:
    selector: DefaultSelector = DefaultSelector()
    server_socket: Socket = Socket()
    server_socket.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1)
    server_socket.setblocking(False)
    server_socket.bind(endpoint)
    server_socket.listen()
    selector.register(server_socket, EVENT_READ, 'server_socket')
    sockets = {}
    clients = {}
    write(stdout.fileno(), f'\x1b[0;34m[i]\x1b[0m Started server at {address}:{port}.\n'.encode())

    try:
        while server_socket:
            key: SelectorKey; mask: int
            for key, mask in selector.select():
                if key.data == 'server_socket':
                    client_socket: Socket; endpoint: tuple[str, int]
                    client_socket, endpoint = server_socket.accept()
                    address: str; port: int
                    address, port = endpoint[0], endpoint[1]
                    write(stdout.fileno(), f'\x1b[0;34m[i]\x1b[0m Connected client at {address}:{port}.\n'.encode())

                    buffer: bytes = client_socket.recv(BUFFER_SIZE)
                    username: str; password: str
                    try:
                        username, password = buffer.decode().split('\n')
                    except ValueError:
                        write(stderr.fileno(), f'\x1b[0;33m[!]\x1b[0m Rejected client at {address}:{port}.\n'.encode())
                        write(stdout.fileno(), f'\x1b[0;34m[i]\x1b[0m Disconnected client at {address}:{port}.\n'.encode())
                        continue
                    pam_authenticator: pam = pam()
                    if pam_authenticator.authenticate(username, password):
                        del password
                        group_identifier: int = getpwnam(username).pw_gid
                        user_identifier: int = getpwnam(username).pw_uid
                        home: str = getpwnam(username).pw_dir
                        shell: str = getpwnam(username).pw_shell
                        process_identifier: int; master_file_descriptor: int
                        process_identifier, master_file_descriptor = fork()
                        if process_identifier == 0:
                            setgid(group_identifier)
                            setuid(user_identifier)
                            environ['USER'] = username
                            environ['LOGNAME'] = username
                            chdir(home)
                            environ['HOME'] = home
                            environ['PWD'] = home
                            execv(shell, [shell, '-il'])
                        else:
                            selector.register(client_socket, EVENT_READ, 'client_socket')
                            selector.register(master_file_descriptor, EVENT_READ, 'master_file_descriptor')
                            sockets[master_file_descriptor] = client_socket
                            clients[client_socket] = {
                                'endpoint': endpoint,
                                'address': address,
                                'port': port,
                                'username': username,
                                'group_identifier': group_identifier,
                                'user_identifier': user_identifier,
                                'process_identifier': process_identifier,
                                'master_file_descriptor': master_file_descriptor
                            }
                        client_socket.setblocking(False)
                        write(stdout.fileno(), f'\x1b[0;32m[+]\x1b[0m Authorized client at {address}:{port}.\n'.encode())
                    else:
                        del password
                        client_socket.close()
                        write(stderr.fileno(), f'\x1b[0;33m[!]\x1b[0m Rejected client at {address}:{port}.\n'.encode())
                        write(stdout.fileno(), f'\x1b[0;34m[i]\x1b[0m Disconnected client at {address}:{port}.\n'.encode())
                elif key.data == 'client_socket':
                    client_socket: Socket = key.fileobj
                    master_file_descriptor: int = clients[client_socket]['master_file_descriptor']
                    buffer: bytes = client_socket.recv(BUFFER_SIZE)
                    if buffer:
                        write(master_file_descriptor, buffer)
                    else:
                        client_socket.close()
                        close(master_file_descriptor)
                        selector.unregister(client_socket)
                        selector.unregister(master_file_descriptor)
                        process_identifier: int = clients[client_socket]['process_identifier']
                        kill(process_identifier, 2)
                        address: str = clients[client_socket]['address']
                        port: int = clients[client_socket]['port']
                        del clients[client_socket]
                        write(stdout.fileno(), f'\x1b[0;34m[i]\x1b[0m Disconnected client at {address}:{port}.\n'.encode())
                elif key.data == 'master_file_descriptor':
                    master_file_descriptor: int = key.fd
                    client_socket: Socket = sockets[master_file_descriptor]
                    try:
                        buffer: bytes = read(master_file_descriptor, BUFFER_SIZE)
                        if buffer:
                            client_socket.sendall(buffer)
                        else:
                            client_socket.close()
                            close(master_file_descriptor)
                            selector.unregister(client_socket)
                            selector.unregister(master_file_descriptor)
                            process_identifier: int = clients[client_socket]['process_identifier']
                            kill(process_identifier, 2)
                            address: str = clients[client_socket]['address']
                            port: int = clients[client_socket]['port']
                            del clients[client_socket]
                            write(stdout.fileno(), f'\x1b[0;34m[i]\x1b[0m Disconnected client at {address}:{port}.\n'.encode())
                    except OSError:
                        client_socket.close()
                        close(master_file_descriptor)
                        selector.unregister(client_socket)
                        selector.unregister(master_file_descriptor)
                        process_identifier: int = clients[client_socket]['process_identifier']
                        kill(process_identifier, 2)
                        address: str = clients[client_socket]['address']
                        port: int = clients[client_socket]['port']
                        del clients[client_socket]
                        write(stdout.fileno(), f'\x1b[0;34m[i]\x1b[0m Disconnected client at {address}:{port}.\n'.encode())
    except KeyboardInterrupt:
        client: Socket
        for client in clients:
            client.sendall(b'\n\r')
        server_socket.close()
        selector.unregister(server_socket)
        write(stdout.fileno(), f'\r\x1b[0;34m[i]\x1b[0m Stopped server at {address}:{port}.\n\r'.encode())
else:
    selector: DefaultSelector = DefaultSelector()
    socket: Socket = Socket()
    socket.connect(endpoint)
    write(stdout.fileno(), f'\x1b[0;34m[i]\x1b[0m Connected to server at {address}:{port}.\n'.encode())
    write(stdout.fileno(), f'\x1b[0;33m[!]\x1b[0m WARNING: Network traffic encryption does NOT take place. Do not use this script outside of localhost. Sending vulnerable information (including the current password to connect) may lead to it getting stolen.\n'.encode())
    try:
        password: str = input(f'\x1b[35m[?]\x1b[0m {username}\'s password: \x1b[8m\x1b[?25l')
    except KeyboardInterrupt:
        write(stdout.fileno(), b'\x1b[0m\x1b[?25h')
        exit(1)
    write(stdout.fileno(), b'\x1b[0m\x1b[?25h')
    socket.sendall(f'{username}\n{password}'.encode())    # sending plaintext passwords over the network :)
    buffer: bytes = socket.recv(BUFFER_SIZE)
    if buffer:
        socket.setblocking(False)
        selector.register(socket, EVENT_READ, 'socket')
        old_attributes: list[Any] = tcgetattr(stdin)
        setraw(stdin)
        selector.register(stdin, EVENT_READ, 'stdin')
        write(stdout.fileno(), f'\x1b[0;32m[+]\x1b[0m Authorized by server at {address}:{port}.\n\r'.encode())
        while socket:
            key: SelectorKey; mask: int
            for key, mask in selector.select():
                if key.data == 'socket':
                    buffer: bytes = socket.recv(BUFFER_SIZE)
                    if buffer and not buffer == b'\n\r':
                        write(stdout.fileno(), buffer)
                    else:
                        if buffer == b'\n\r':
                            write(stdout.fileno(), buffer)
                        socket.close()
                        selector.unregister(socket)
                        selector.unregister(stdin)
                        write(stdout.fileno(), f'\x1b[0;34m[i]\x1b[0m Disconnected by server at {address}:{port}.\n\r'.encode())
                        tcsetattr(stdin, TCSADRAIN, old_attributes)
                        exit(1)
                elif key.data == 'stdin':
                    buffer: bytes = read(stdin.fileno(), BUFFER_SIZE)
                    socket.sendall(buffer)
    else:
        write(stdout.fileno(), f'\x1b[0;33m[!]\x1b[0m Rejected by server at {address}:{port}.\n'.encode())
        write(stdout.fileno(), f'\x1b[0;34m[i]\x1b[0m Disconnected by server at {address}:{port}.\n\r'.encode())